
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace CMSProject.Models
{

using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Web.Mvc;

    public partial class Blog
{

    public int BlogID { get; set; }

    public string BlogTitle { get; set; }

    public Nullable<int> CategoryID { get; set; }
     [AllowHtml]
     [DataType(DataType.MultilineText)]
    public string BlogContent { get; set; }

    public string Author { get; set; }

    public Nullable<System.DateTime> DateCreated { get; set; }



    public virtual Category Category { get; set; }

}

}
