
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace CMSProject.Models
{

using System;
    using System.Collections.Generic;
    
public partial class GoodsReceipt
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public GoodsReceipt()
    {

        this.GoodsReceiptDetails = new HashSet<GoodsReceiptDetail>();

    }


    public int GoodsReceiptID { get; set; }

    public Nullable<int> SupplierID { get; set; }

    public string GoodsReceiptName { get; set; }

    public Nullable<System.DateTime> AddedDate { get; set; }

    public string Creator { get; set; }

    public Nullable<byte> Status { get; set; }

    public Nullable<decimal> Total { get; set; }



    public virtual Supplier Supplier { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<GoodsReceiptDetail> GoodsReceiptDetails { get; set; }

}

}
