
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace CMSProject.Models
{

using System;
    using System.Collections.Generic;
    
public partial class Order
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Order()
    {

        this.OrderDetails = new HashSet<OrderDetail>();

    }


    public int OrderID { get; set; }

    public Nullable<byte> OrderName { get; set; }

    public Nullable<int> CustomerID { get; set; }

    public string CustomerName { get; set; }

    public string CustomerEmail { get; set; }

    public Nullable<byte> Gender { get; set; }

    public string Phone { get; set; }

    public string ShipAddress { get; set; }

    public string OrderCreate { get; set; }

    public Nullable<System.DateTime> CreateDate { get; set; }

    public string Shipper { get; set; }

    public Nullable<System.DateTime> ShipDate { get; set; }

    public string Receiver { get; set; }

    public Nullable<System.DateTime> PayDate { get; set; }

    public Nullable<decimal> Total { get; set; }

    public string Note { get; set; }

    public Nullable<byte> Status { get; set; }



    public virtual Customer Customer { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<OrderDetail> OrderDetails { get; set; }

}

}
