
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace CMSProject.Models
{

using System;
    using System.Collections.Generic;
    
public partial class OrderReport
{

    public int OrderReportID { get; set; }

    public string CustomerID { get; set; }

    public Nullable<System.DateTime> CreatedDay { get; set; }

    public Nullable<double> Interest { get; set; }

}

}
